// <auto-generated />
namespace Softensity.Hatley.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddedEnabledfieldtoaccountstables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedEnabledfieldtoaccountstables));
        
        string IMigrationMetadata.Id
        {
            get { return "201410191632544_Added Enabled field to accounts tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
